apiVersion: openchoreo.dev/v1alpha1
kind: DeployableArtifact
metadata:
  # Unique name of the deployable artifact within the deployment track (namespace).
  #
  # If the deployable artifact is created by the build, the name will be in
  # the format of <buildName>-<hash>
  # where the hash is a system generated string based on the Build spec.
  # This hash ensures the each spec changes will create a unique deployable artifact.
  #
  # +required
  # +immutable
  name: test-deployable-artifact-hansi
  # Organization name that the resource belongs to.
  #
  # +immutable
  namespace: default
  annotations:
    # Display name of the deployable artifact.
    #
    # +required
    openchoreo.dev/display-name: Test Deployable Artifact Hansi
    # Description of the deployable artifact.
    #
    # +optional
    openchoreo.dev/description: Test Deployable Artifact Description
  labels:
    # Deployment track that this deployable artifact belongs to.
    #
    # +required
    # +immutable
    openchoreo.dev/deployment-track: test-deployment-track-hansi
    # Component name that this deployable artifact belongs to.
    #
    # +required
    # +immutable
    openchoreo.dev/component: reading-list-service-hansi
    # Project name that this deployable artifact belongs to.
    #
    # +required
    # +immutable
    openchoreo.dev/project: default
    # Organization name that the resource belongs to.
    #
    # +required
    # +immutable
    openchoreo.dev/organization: default
spec:
  # Reference to the artifact that is being deployed.
  #
  # +required
  targetArtifact:
    # Reference to the build that produced this deployable artifact. This filed is automatically
    # populated by the build upon successful build if this resource is created by the build.
    # If the field is set by the user, this deployable artifact will refer to an existing build.
    #
    # This field is mutually exclusive with the other fields.
    #
    # +optional
    fromBuildRef:
      # Name of the build to retrieve the deployable artifact. This field is automatically
      # populated by the build upon successful build if this resource is created by the build.
      # If the field is set by the user, this deployable artifact will refer to an existing build.
      #
      # This field is mutually exclusive with the other fields.
      #
      # +optional
      name: reading-list-service-hansi-build-01
      # Refer to a build that has the given git revision in the build spec.
      # If there are multiple builds with the same git revision is present, the latest build will be selected.
      #
      # This field is mutually exclusive with the other fields.
      #
      # +optional
      gitRevision: c35865df15cca746101f32428eceebf48ef1f8f6
    # Reference to the image tag that is being deployed. This filed will be only applicable
    # to the component types that has image as the source.
    #
    # This field is mutually exclusive with the other fields.
        
