apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: reading-list-service-hansi-4
  namespace: default
spec:
  owner:
    projectName: default
  type: Service
  build:
    repository:
      appPath: /service-go-reading-list
      revision:
        branch: main
      url: https://github.com/hanzjk/sample-workloads
    templateRef:
      name: buildpack-ci

---
apiVersion: openchoreo.dev/v1alpha1
kind: Build
metadata:
  name: reading-list-service-hansi-build-04
  namespace: default
spec:
  owner:
    componentName: reading-list-service-hansi-4
    projectName: default
  repository:
    appPath: /service-go-reading-list
    revision:
      branch: main
    url: https://github.com/hanzjk/sample-workloads
  templateRef:
    name: buildpack-ci
---
apiVersion: openchoreo.dev/v1alpha1
kind: Service
metadata:
  name: reading-list-service-hansi-4
  namespace: default
spec:
  owner:
    componentName: reading-list-service-hansi-4
    projectName: default
  workloadName: reading-list-service-hansi-4-workload
  className: default
  apis:
    reading-list-api: 
      type: REST
      className: default
      rest:
        backend:
          port: 8080
          basePath: /api/v1/reading-list
        exposeLevels: [ "Public" ]
